const CHARSETS={lowercase:'abcdefghijklmnopqrstuvwxyz',uppercase:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',numbers:'0123456789',symbols:'!@#$%^&*()-_=+[]{};:,.<>?/|~'};
const AMBIGUOUS=new Set('0Oo1Il|');
const WORDS=['amber','anchor','apple','arrow','atlas','aurora','bamboo','beacon','birch','bison','blaze','bloom','blue','bravo','breeze','brook','cactus','canyon','cedar','cherry','cinder','citrus','cloud','cobalt','comet','coral','cosmos','crane','crystal','dawn','delta','drift','dune','echo','ember','falcon','fern','fjord','flame','flora','forest','frost','galaxy','garden','glacier','glow','granite','harbor','hazel','horizon','island','jade','juniper','lagoon','lantern','lemon','lilac','lunar','maple','marble','meadow','meteor','mist','monarch','moon','moss','nebula','nova','oasis','ocean','olive','onyx','orbit','orchid','otter','pearl','pepper','phoenix','pine','pluto','pond','quartz','raven','reef','river','robin','rocket','rose','sage','shadow','shore','silver','solar','sparrow','spruce','star','stone','storm','summit','sunset','tiger','timber','topaz','trail','tulip','valley','violet','wave','willow','winter','wolf','zephyr'];
const state={mode:'password',results:[]};
const $=id=>document.getElementById(id);
const els={passwordControls:$('passwordControls'),passphraseControls:$('passphraseControls'),generatorTitle:$('generatorTitle'),lengthRange:$('lengthRange'),lengthNumber:$('lengthNumber'),lowercase:$('lowercase'),uppercase:$('uppercase'),numbers:$('numbers'),symbols:$('symbols'),excludeAmbiguous:$('excludeAmbiguous'),noRepeats:$('noRepeats'),startWithLetter:$('startWithLetter'),excludedChars:$('excludedChars'),wordCount:$('wordCount'),separator:$('separator'),capitalizeWords:$('capitalizeWords'),appendNumber:$('appendNumber'),appendSymbol:$('appendSymbol'),quantity:$('quantity'),generateButton:$('generateButton'),copyAllButton:$('copyAllButton'),resetButton:$('resetButton'),results:$('results'),resultCount:$('resultCount'),errorMessage:$('errorMessage'),strengthLabel:$('strengthLabel'),entropyValue:$('entropyValue'),strengthMeter:$('strengthMeter'),strengthDetail:$('strengthDetail'),themeToggle:$('themeToggle'),toast:$('toast')};
function randomInt(max){if(!Number.isSafeInteger(max)||max<=0)throw new Error('Invalid random range.');const top=0x100000000,limit=top-(top%max),buf=new Uint32Array(1);let n;do{crypto.getRandomValues(buf);n=buf[0]}while(n>=limit);return n%max}
function pick(str,used=null){if(!str.length)throw new Error('A selected character set is empty.');if(!used)return str[randomInt(str.length)];const available=[...str].filter(ch=>!used.has(ch));if(!available.length)throw new Error('Not enough unique characters for these settings.');const ch=available[randomInt(available.length)];used.add(ch);return ch}
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=randomInt(i+1);[items[i],items[j]]=[items[j],items[i]]}return items}
function clampLength(v){const n=parseInt(v,10);return Number.isNaN(n)?20:Math.min(128,Math.max(4,n))}
function passwordConfig(){const length=clampLength(els.lengthNumber.value),excluded=new Set(els.excludedChars.value.split(''));if(els.excludeAmbiguous.checked)AMBIGUOUS.forEach(ch=>excluded.add(ch));const selected=[];for(const key of ['lowercase','uppercase','numbers','symbols']){if(!els[key].checked)continue;const chars=[...CHARSETS[key]].filter(ch=>!excluded.has(ch)).join('');if(!chars)throw new Error(`${key} has no characters left after exclusions.`);selected.push({key,chars})}if(!selected.length)throw new Error('Select at least one character set.');if(length<selected.length)throw new Error(`Length must be at least ${selected.length}.`);const pool=[...new Set(selected.map(g=>g.chars).join(''))].join('');if(els.noRepeats.checked&&length>pool.length)throw new Error(`No-repeat mode has only ${pool.length} available unique characters.`);if(els.startWithLetter.checked&&!selected.some(g=>g.key==='lowercase'||g.key==='uppercase'))throw new Error('Start-with-letter requires lowercase and/or uppercase.');return{length,selected,pool,noRepeats:els.noRepeats.checked,startWithLetter:els.startWithLetter.checked}}
function generatePassword(c){const used=c.noRepeats?new Set():null,chars=[];for(const g of c.selected)chars.push(pick(g.chars,used));while(chars.length<c.length)chars.push(pick(c.pool,used));shuffle(chars);if(c.startWithLetter){const letters=CHARSETS.lowercase+CHARSETS.uppercase,index=chars.findIndex(ch=>letters.includes(ch));if(index>0)[chars[0],chars[index]]=[chars[index],chars[0]]}return chars.join('')}
function passwordEntropy(c){if(c.noRepeats){let bits=0;for(let i=0;i<c.length;i++)bits+=Math.log2(Math.max(1,c.pool.length-i));return Math.max(0,bits)}return c.length*Math.log2(c.pool.length)}
function phraseConfig(){return{count:Math.min(8,Math.max(3,parseInt(els.wordCount.value,10)||4)),separator:els.separator.value,capitalize:els.capitalizeWords.checked,number:els.appendNumber.checked,symbol:els.appendSymbol.checked}}
function generatePhrase(c){const words=[];for(let i=0;i<c.count;i++){let w=WORDS[randomInt(WORDS.length)];if(c.capitalize)w=w[0].toUpperCase()+w.slice(1);words.push(w)}let result=words.join(c.separator);if(c.number)result+=c.separator+String(randomInt(90)+10);if(c.symbol)result+=CHARSETS.symbols[randomInt(CHARSETS.symbols.length)];return result}
function phraseEntropy(c){let bits=c.count*Math.log2(WORDS.length);if(c.number)bits+=Math.log2(90);if(c.symbol)bits+=Math.log2(CHARSETS.symbols.length);return bits}
function rating(bits){if(bits<40)return{label:'Weak',pct:22,detail:'Increase length, word count, or complexity.'};if(bits<60)return{label:'Fair',pct:45,detail:'Usable for lower-risk situations, but stronger settings are recommended.'};if(bits<85)return{label:'Strong',pct:72,detail:'Strong for most account use when stored safely and used only once.'};return{label:'Excellent',pct:100,detail:'A large estimated search space with strong random generation.'}}
function renderStrength(bits){const r=rating(bits);els.entropyValue.textContent=Math.round(bits);els.strengthLabel.textContent=r.label;els.strengthMeter.style.width=`${r.pct}%`;els.strengthDetail.textContent=r.detail}
function renderResults(){els.results.replaceChildren();state.results.forEach((value,i)=>{const row=document.createElement('div');row.className='result-item';const text=document.createElement('div');text.className='password-value';text.textContent=value;const button=document.createElement('button');button.className='copy-button';button.type='button';button.textContent='Copy';button.addEventListener('click',()=>copyText(value,`Result ${i+1} copied`));row.append(text,button);els.results.append(row)});const n=state.results.length;els.resultCount.textContent=`${n} result${n===1?'':'s'}`;els.copyAllButton.disabled=n===0}
function generate(){els.errorMessage.textContent='';try{const qty=parseInt(els.quantity.value,10)||1;if(state.mode==='password'){const c=passwordConfig();state.results=Array.from({length:qty},()=>generatePassword(c));renderStrength(passwordEntropy(c))}else{const c=phraseConfig();state.results=Array.from({length:qty},()=>generatePhrase(c));renderStrength(phraseEntropy(c))}renderResults()}catch(err){state.results=[];renderResults();els.errorMessage.textContent=err.message||'Unable to generate with those settings.'}}
async function copyText(text,msg='Copied'){try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}toast(msg)}
let toastTimer;function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),1600)}
const PRESETS={balanced:{length:20,lower:true,upper:true,numbers:true,symbols:true,ambiguous:true,repeats:false,first:false},strong:{length:24,lower:true,upper:true,numbers:true,symbols:true,ambiguous:true,repeats:false,first:false},maximum:{length:40,lower:true,upper:true,numbers:true,symbols:true,ambiguous:false,repeats:false,first:false},easy:{length:18,lower:true,upper:true,numbers:true,symbols:false,ambiguous:true,repeats:false,first:true},pin:{length:6,lower:false,upper:false,numbers:true,symbols:false,ambiguous:false,repeats:false,first:false}};
const PHRASE_PRESETS={standard:{count:4,separator:'-',capitalize:true,number:true,symbol:false},strong:{count:6,separator:'-',capitalize:true,number:true,symbol:true},compact:{count:3,separator:'-',capitalize:false,number:true,symbol:false}};
function setLength(v){const n=clampLength(v);els.lengthRange.value=String(n);els.lengthNumber.value=String(n)}
function applyPreset(name){const p=PRESETS[name];if(!p)return;setLength(p.length);els.lowercase.checked=p.lower;els.uppercase.checked=p.upper;els.numbers.checked=p.numbers;els.symbols.checked=p.symbols;els.excludeAmbiguous.checked=p.ambiguous;els.noRepeats.checked=p.repeats;els.startWithLetter.checked=p.first;els.excludedChars.value='';document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));generate()}
function applyPhrasePreset(name){const p=PHRASE_PRESETS[name];if(!p)return;els.wordCount.value=String(p.count);els.separator.value=p.separator;els.capitalizeWords.checked=p.capitalize;els.appendNumber.checked=p.number;els.appendSymbol.checked=p.symbol;document.querySelectorAll('.phrase-preset').forEach(b=>b.classList.toggle('active',b.dataset.phrasePreset===name));generate()}
function markCustom(){document.querySelectorAll('.preset').forEach(b=>b.classList.remove('active'))}
function setMode(mode){state.mode=mode==='passphrase'?'passphrase':'password';els.passwordControls.hidden=state.mode!=='password';els.passphraseControls.hidden=state.mode!=='passphrase';els.generatorTitle.textContent=state.mode==='password'?'Build your password':'Build your passphrase';document.querySelectorAll('.mode-button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));generate()}
function reset(){els.quantity.value='1';if(state.mode==='password')applyPreset('balanced');else applyPhrasePreset('standard')}
function initTheme(){try{const saved=localStorage.getItem('neo-password-theme');if(saved==='light'||saved==='dark')document.documentElement.dataset.theme=saved}catch{}}
function toggleTheme(){const current=document.documentElement.dataset.theme==='light'?'light':'dark',next=current==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('neo-password-theme',next)}catch{}}
els.lengthRange.addEventListener('input',e=>{setLength(e.target.value);markCustom();generate()});els.lengthNumber.addEventListener('change',e=>{setLength(e.target.value);markCustom();generate()});['lowercase','uppercase','numbers','symbols','excludeAmbiguous','noRepeats','startWithLetter'].forEach(k=>els[k].addEventListener('change',()=>{markCustom();generate()}));els.excludedChars.addEventListener('input',()=>{markCustom();generate()});['wordCount','separator','capitalizeWords','appendNumber','appendSymbol','quantity'].forEach(k=>els[k].addEventListener('change',generate));els.generateButton.addEventListener('click',generate);els.resetButton.addEventListener('click',reset);els.copyAllButton.addEventListener('click',()=>copyText(state.results.join('\n'),'All results copied'));els.themeToggle.addEventListener('click',toggleTheme);document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));document.querySelectorAll('.phrase-preset').forEach(b=>b.addEventListener('click',()=>applyPhrasePreset(b.dataset.phrasePreset)));document.querySelectorAll('.mode-button').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));document.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key==='Enter'){e.preventDefault();generate()}if(mod&&e.shiftKey&&e.key.toLowerCase()==='c'&&state.results[0]){e.preventDefault();copyText(state.results[0],'First result copied')}});initTheme();generate();
